# Generated by Django 5.2.6 on 2025-11-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_alter_consultation_patient_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=100)),
                ('quantite', models.CharField(max_length=50)),
                ('contenant', models.CharField(max_length=50)),
                ('duree', models.PositiveIntegerField(help_text='Durée en jours')),
                ('posologie', models.TextField(help_text='Détails de la posologie (ex : matin et soir)')),
                ('frequence', models.CharField(help_text='ex: 2 fois par jour', max_length=50)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='medico.consultation')),
            ],
        ),
    ]
